# Generated by Django 3.1.4 on 2021-01-31 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_app', '0002_auto_20210131_2316'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'name')},
        ),
    ]
